name: Vitest and Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # INSTALL DEPS
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
  # VITEST JOB
  test:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Vitest
        run: npm run test
  # ESLINT JOB
  lint:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
